### PR TITLE
Accordion component design

### PR DESCRIPTION
**Pull request by AranzazuVM**
Added files to stories
Added css and tokens

### CODE REVIEW

**Comment by alexsteele95** [comment]
Now looking into this

**Comment by jgonza16** [comment]
add styles tokens and look and feels

default:
image
material:
image

**Comment by daniele-zurico** [comment]
@jgonza16 @AranzazuVM my feeling is that the content should be aligned with the header or something like that instead it's squashed with the border:

Screenshot 2024-07-29 at 17 30 54

am I correct?

reference: https://m1.material.io/components/expansion-panels.html#expansion-panels-behavior

**Comment by alexwbbr** [comment]
> @jgonza16 @AranzazuVM my feeling is that the content should be aligned with the header or something like that instead it's squashed with the border:
> 
> am I correct?
> 
> reference: https://m1.material.io/components/expansion-panels.html#expansion-panels-behavior

I agree, there should be some padding inside the content area. We can add that property to the css tokens so the user can always fine tune it later but there should be some by default

**Review by Ibabalola — DISMISSED** [review]

**Comment by jgonza16** [comment]
@daniele-zurico and @alexwbbr yep!! it's true that both padding you can set value token way but i have updated the same default value. Done!

**Review by alexwbbr — APPROVED** [review]

**Review by daniele-zurico — APPROVED** [review]

**Pull request merged**
